### ISSUE TITLE
Menu item added but not showing

### ISSUE THREAD

**Issue by danchann** [andrewlaw111/NodeJS-Restaurant-App#8]
![clipboard01](https://user-images.githubusercontent.com/3872230/40072356-273a5fa6-58a6-11e8-9d5e-bca71bb419a0.jpg)
![clipboard02](https://user-images.githubusercontent.com/3872230/40072362-2be1262a-58a6-11e8-8ea1-23940acd1f64.jpg)

**Comment by andrewlaw111** [comment]
This is a feature. You need to change the name.
